server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username: e3mall
    password: 123456
    druid:
      initial-size: 2 #初始化建立物理连接的个数
      min-idle: 2 #最小连接池数量
      max-active: 50 #最大连接池数量
      validation-query: SELECT 1 #用来检测连接是否有效
      test-while-idle: true #申请连接的时候检测，如果有空闲时间大于，则检测连接是否有效
      aop-patterns: com.tfjybj.physical.*
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
  redis:
    database: 0
    host: 112.126.72.101
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    mapUnderscoreToCamelCase: true #设置数据库字段名到JavaBean实体类属性命的自动驼峰转换
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: ID_WORKER_STR




